# Generated by Django 3.0.7 on 2020-06-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200615_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmString',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
