# Generated by Django 3.0.7 on 2020-06-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('continent', models.CharField(default='亚洲', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('confirm_add', models.IntegerField(default=0)),
                ('confirm', models.IntegerField(default=0)),
                ('heal', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE,
                                              to='COVID_19Analyse.Country')),
            ],
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['continent'], name='COVID_19Ana_contine_eac69c_idx'),
        ),
        migrations.AddIndex(
            model_name='countrydata',
            index=models.Index(fields=['country'], name='COVID_19Ana_country_b78e4a_idx'),
        ),
    ]
