# Generated by Django 3.0.7 on 2020-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19Analyse', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='countrydata',
            index=models.Index(fields=['date'], name='COVID_19Ana_date_0c735e_idx'),
        ),
        migrations.AddIndex(
            model_name='countrydata',
            index=models.Index(fields=['country', 'date'], name='COVID_19Ana_country_1fd38c_idx'),
        ),
    ]
